/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit;

/**
 *
 * @author Acer
 */
public class CheetSheetWindow extends javax.swing.JFrame {

    /**
     * Creates new form CheetSheetWindow
     */
    public CheetSheetWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CheetSheet");
        getContentPane().setLayout(new java.awt.GridLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("?\tminimálne 0-krát, maximálne raz\n*\tminimálne 0-krát\n+\tminimálne raz\n{n}\tpráve n-krát\n{m, n}\tminimálne m-krát, maximálne n-krát\n{m, }\tminimálne m-krát\n-------------------------------------------------------------------------------------------------------\n\\d\tčíslice 0-9\n\\D\takýkoľvek znak okrem 0-9\n\\w\tznaky slova ([a-zA-Z0-9_])\n\\W\takýkoľvek znak okrem znakov slova\n\\s\tbiele znaky\n\\S\takýkoľvek znak okrem bielych znakov\n-------------------------------------------------------------------------------------------------------\n^\tzačiatok reťazca (v ktorom sa vyhľadáva)\n$\tkoniec reťazca (v ktorom sa vyhľadáva)\n.\takýkoľvek znak\n-------------------------------------------------------------------------------------------------------\n\\\tignorovanie špeciálneho znaku\n( )\tznaky zoskupovania\n[ ]\trozsah hodnôt, príklad [a-z]\n|\tzhoda s predhcádzajucim alebo nasledujúcim\n");
        jTextArea1.setPreferredSize(new java.awt.Dimension(475, 475));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
